### ISSUE TITLE
Reproduce the Jenkins CI linux build locally

### ISSUE THREAD

**Issue by j-rivero** [gazebo-tooling/release-tools#923]
It should be possible trying to reproduce a Linux build on Jenkins in a local system in a non very difficult way. They mainly consist in a Docker enviroment + build.sh script and a custom way of running them in using `docker run` parameters. 

Roadmap:
 
 * [x] Export `Dockerfile` and `build.sh` from each Linux build https://github.com/gazebo-tooling/release-tools/pull/279
 * [ ] Fix hard-coded paths and values in Dockerfile and build.sh so a local system can run them without modifications. Goal is also to be able to run them using rocker and all the user developer tools via `--home`.
 * [ ] Use an easy way for running docker build + docker run with all the arguments setup correctly.
 * [ ] Find a quick way of setting the whole thing just by passing a Jenkins URL. Probably a `gzdev` small module.

**Comment by j-rivero** [comment]
> Use an easy way for running docker build + docker run with all the arguments setup correctly.

docker build uses `$USER/$GUI/$UID` variables from active session. Can not find a way of using devcontainer.json file to include them.

Using docker compose it is also not fully clean since [UID/GUI seems not easy to deal with](https://github.com/compose-spec/compose-go/pull/299):
```yaml
services:
  jenkins-build:
    image: buildoo/jenkinsbuild
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GID: ${GID}
        USERID: ${USERID}
        USER: ${USER}
``` 
Via:
```bash
USERID=$(id -u) GID=$(id -g) docker compose up
```

**Comment by j-rivero** [comment]
While debugging an `-install-` type of job, I've been developing the compose configuration to something that is usable to reproduce the build locally for an X kind of job:

```yaml
services:
  jenkins-build:
    image: buildoo/jenkinsbuild
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GID: ${GID}
        USERID: ${USERID}
        USER: ${USER}
  run-jenkins-build:
    image: buildoo/jenkinsbuild
    stdin_open: true 
    tty: true
    environment:
        - DISPLAY=unix${DISPLAY}
        - TERM=xterm-256color
        - GID=${GID}
        - USERID=${USERID}
        - USER=${USER}
    volumes:
        - /sys:/sys:ro
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - /dev/log:/dev/log:ro
        - /run/log:/run/log:ro
    entrypoint: ['./build.sh']
```

Via:

```
USERID=$(id -u) GID=$(id -g) docker compose build
USERID=$(id -u) GID=$(id -g) docker compose run --rm run-jenkins-build
```

That will reproduce the build of for example https://build.osrfoundation.org/job/ros_gzharmonic_bridge-install-pkg_iron-ci-jammy-amd64 . To obtain a debugging shell in the fail of the `build.sh` command, we will need to add to that script the bash trap:
```
trap "/bin/bash" 0 INT QUIT ABRT PIPE TERM
``

**Comment by j-rivero** [comment]
The noble images could be currently broken since they have a default ubuntu user with UID 1000. This could match the local user UID hence broken.

**Comment by j-rivero** [comment]
After #1191, the SHELL_ON_ERRORS var is ready, the code could be something like:
```
services:
  jenkins-build:
    image: buildoo/jenkinsbuild
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GID: ${GID}
        USERID: ${USERID}
        USER: ${USER}
  run-jenkins-build:
    image: buildoo/jenkinsbuild
    stdin_open: true 
    tty: true
    environment:
        - DISPLAY=unix${DISPLAY}
        - TERM=xterm-256color
        - GID=${GID}
        - USERID=${USERID}
        - USER=${USER}
        - SHELL_ON_ERRORS=true
    volumes:
        - /sys:/sys:ro
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - /dev/log:/dev/log:ro
        - /run/log:/run/log:ro
    entrypoint: ['./build.sh']
```
